### ISSUE TITLE
ERROR: Directory '.[figures]' is not installable

### ISSUE THREAD

**Issue by HR320** [Howland-Lab/Unified-Momentum-Model#1]
Hi,
I get the error messages 
ERROR: Directory '.[figures]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.mentumModel

Python 3.11.8 64bit

What is the reason?

Thanks
HR

**Comment by HR320** [comment]
Thanks. but now I have 2 directories with the unified-momentum-model, one created with the MS powershell and one created with the MS Terminal in a virtual environment. Do I have to uninstall one of it?
And even more error messages in Visual studio code running the example_01_classical_vs_unified.py

**Comment by kirbyh** [comment]
> I tried pip install . and pip install .[figures]

Please double check that you are in the correct directory (`Unified-Momentum-Model`) when installing the repository, for example: 
```
git clone https://github.com/Howland-Lab/Unified-Momentum-Model.git
cd Unified-Momentum-Model
pip install .[figures]
```

You can also try installing into a fresh virtual environment: 
```
git clone https://github.com/Howland-Lab/Unified-Momentum-Model.git
cd Unified-Momentum-Model
python -m venv .venv
```
source the virtual environment `.venv/Scripts/Activate.ps1` (Windows) or `source .venv/bin/activate` (unix), then: 
```
pip install .[figures]
```
